version: '3.7'

services:
  deliveryservice.db:
    image: mysql:5.7
    ports:
      - "33061:3306"
    volumes:
      - deliveryservicedbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=defaultdb
      - MYSQL_ROOT_PASSWORD=Password123
  
  deliveryservice.db.migrations:
    depends_on:
      - deliveryservice.db
    image: deliveryservice.db.migrations
    build:
      context: ./db/
      dockerfile: Dockerfile
    command: -cs "server=deliveryservice.db;database=defaultdb;uid=root;password=Password123;SslMode=None;"

volumes:
  deliveryservicedbdata: